-- PostgreSQL/Supabase schema inferred from the supplied NU CSV exports.
-- Column order intentionally matches each CSV so that dashboard CSV imports work.

begin;

create table if not exists public.nu_users (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone,
    username text,
    email text not null,
    role smallint not null default 0,
    firstname text,
    lastname text,
    middlename text,
    ext text,
    phone text,
    is_active boolean,
    date_time_email_confirmed timestamp with time zone,
    admin_confirmed_by bigint,
    admin_confirmed_date_time timestamp with time zone,
    user_qr_code text,
    "userID" uuid,
    salutation text,
    current_points integer,
    "supabaseProfileImageUrl" text,
    "bio note" text,
    constraint nu_users_current_points_nonnegative
        check (current_points is null or current_points >= 0)
);

create table if not exists public.nu_buildings (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    building_name text not null,
    address text,
    created_by bigint,
    date_time_last_updated timestamp with time zone,
    last_updated_by bigint
);

create table if not exists public.nu_departments (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    department_name text not null,
    created_by bigint,
    last_updated_date_time timestamp with time zone,
    last_updated_by bigint
);

create table if not exists public.nu_floors (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    building_id bigint not null,
    created_by bigint,
    date_time_last_updated timestamp with time zone,
    last_updated_by bigint,
    floor_name text not null,
    constraint nu_floors_building_fk
        foreign key (building_id) references public.nu_buildings (id)
        on update cascade on delete restrict
);

create table if not exists public.nu_rooms (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    room_no text not null,
    building_id bigint not null,
    floor_id bigint not null,
    created_by bigint,
    last_updated_by bigint,
    date_time_last_updated timestamp with time zone,
    room_max_capacity integer,
    constraint nu_rooms_capacity_positive
        check (room_max_capacity is null or room_max_capacity > 0),
    constraint nu_rooms_building_fk
        foreign key (building_id) references public.nu_buildings (id)
        on update cascade on delete restrict,
    constraint nu_rooms_floor_fk
        foreign key (floor_id) references public.nu_floors (id)
        on update cascade on delete restrict
);

create table if not exists public.nu_places (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    place_name text not null,
    room_id bigint not null,
    created_by bigint,
    last_updated_by bigint,
    date_time_last_updated timestamp with time zone,
    direction text,
    department_id bigint,
    constraint nu_places_room_fk
        foreign key (room_id) references public.nu_rooms (id)
        on update cascade on delete restrict,
    constraint nu_places_department_fk
        foreign key (department_id) references public.nu_departments (id)
        on update cascade on delete set null
);

create table if not exists public.nu_events (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    event_name text not null,
    created_by bigint,
    event_description text not null,
    event_theme text,
    schedule_id bigint,
    theme_colors text,
    qrcode_value text,
    event_head_organizer_id bigint,
    event_topics text,
    event_host_user_id bigint,
    start_datetime timestamp with time zone not null,
    end_datetime timestamp with time zone not null,
    place_id bigint,
    status text not null default 'draft',
    constraint nu_events_datetime_order
        check (end_datetime >= start_datetime),
    constraint nu_events_place_fk
        foreign key (place_id) references public.nu_places (id)
        on update cascade on delete set null
);

create table if not exists public.nu_certificate_templates (
    id uuid primary key default gen_random_uuid(),
    event_id bigint,
    type text not null,
    name text not null,
    asset_path text not null,
    config jsonb,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    constraint nu_certificate_templates_event_fk
        foreign key (event_id) references public.nu_events (id)
        on update cascade on delete cascade
);

create table if not exists public.nu_certificates (
    id uuid primary key default gen_random_uuid(),
    event_id bigint not null,
    type text not null,
    status text not null default 'pending',
    recipient_name text not null,
    recipient_email text not null,
    verification_code text not null,
    issued_at timestamp with time zone,
    revoked_at timestamp with time zone,
    file_path text,
    created_at timestamp with time zone not null default now(),
    constraint nu_certificates_event_fk
        foreign key (event_id) references public.nu_events (id)
        on update cascade on delete cascade,
    constraint nu_certificates_verification_code_unique
        unique (verification_code)
);

create table if not exists public.nu_certificate_audits (
    id uuid primary key default gen_random_uuid(),
    certificate_id uuid not null,
    action text not null,
    actor_user_id uuid,
    metadata jsonb,
    created_at timestamp with time zone not null default now(),
    constraint nu_certificate_audits_certificate_fk
        foreign key (certificate_id) references public.nu_certificates (id)
        on update cascade on delete cascade
);

create table if not exists public.nu_event_sessions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    session_topic text not null,
    session_speaker_id text,
    session_date date not null,
    session_start_time time without time zone not null,
    session_end_time time without time zone not null,
    session_building_id bigint not null,
    session_floor_id bigint not null,
    session_room_id bigint not null,
    session_event_id bigint not null,
    session_type smallint not null default 1,
    session_max_capacity integer,
    status smallint not null default 1,
    constraint nu_event_sessions_type_valid
        check (session_type in (1, 2)),
    constraint nu_event_sessions_status_valid
        check (status in (0, 1)),
    constraint nu_event_sessions_capacity_positive
        check (session_max_capacity is null or session_max_capacity > 0),
    constraint nu_event_sessions_building_fk
        foreign key (session_building_id) references public.nu_buildings (id)
        on update cascade on delete restrict,
    constraint nu_event_sessions_floor_fk
        foreign key (session_floor_id) references public.nu_floors (id)
        on update cascade on delete restrict,
    constraint nu_event_sessions_room_fk
        foreign key (session_room_id) references public.nu_rooms (id)
        on update cascade on delete restrict,
    constraint nu_event_sessions_event_fk
        foreign key (session_event_id) references public.nu_events (id)
        on update cascade on delete cascade
);

create table if not exists public.nu_event_attendees (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    user_id uuid,
    event_id bigint not null,
    date_time_first_in timestamp without time zone,
    date_time_last_out timestamp without time zone,
    date_index integer,
    status smallint not null default 0,
    session_id bigint not null,
    certificate_url text,
    constraint nu_event_attendees_date_index_nonnegative
        check (date_index is null or date_index >= 0),
    constraint nu_event_attendees_status_valid
        check (status in (0, 1, 2, 67)),
    constraint nu_event_attendees_event_fk
        foreign key (event_id) references public.nu_events (id)
        on update cascade on delete cascade
);

create table if not exists public.nu_event_attendees_log (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    event_id bigint not null,
    user_id uuid,
    date_time timestamp without time zone not null,
    date_index integer,
    session_id bigint not null,
    log_type smallint not null,
    constraint nu_event_attendees_log_date_index_nonnegative
        check (date_index is null or date_index >= 0),
    constraint nu_event_attendees_log_type_valid
        check (log_type in (1, 2, 67)),
    constraint nu_event_attendees_log_event_fk
        foreign key (event_id) references public.nu_events (id)
        on update cascade on delete cascade
);

create table if not exists public.nu_event_question (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    event_id bigint not null,
    date_index integer not null,
    question text not null,
    user_id uuid not null,
    status smallint not null default 0,
    reply_by_speaker_handler text,
    speaker_id text,
    constraint nu_event_question_date_index_nonnegative
        check (date_index >= 0)
);

create table if not exists public.nu_user_note (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    user_id uuid not null,
    note_content text not null,
    for_event_id bigint not null,
    date_index integer not null,
    session_id bigint,
    constraint nu_user_note_date_index_nonnegative
        check (date_index >= 0)
);

create index if not exists nu_users_auth_user_id_idx
    on public.nu_users ("userID");
create index if not exists nu_users_email_idx
    on public.nu_users (email);
create index if not exists nu_floors_building_id_idx
    on public.nu_floors (building_id);
create index if not exists nu_rooms_location_idx
    on public.nu_rooms (building_id, floor_id);
create index if not exists nu_places_room_id_idx
    on public.nu_places (room_id);
create index if not exists nu_places_department_id_idx
    on public.nu_places (department_id);
create index if not exists nu_events_start_datetime_idx
    on public.nu_events (start_datetime);
create index if not exists nu_events_status_idx
    on public.nu_events (status);
create index if not exists nu_certificate_templates_event_id_idx
    on public.nu_certificate_templates (event_id);
create index if not exists nu_certificates_event_recipient_idx
    on public.nu_certificates (event_id, recipient_email);
create index if not exists nu_certificate_audits_certificate_id_idx
    on public.nu_certificate_audits (certificate_id);
create index if not exists nu_event_sessions_event_date_idx
    on public.nu_event_sessions (session_event_id, session_date);
create index if not exists nu_event_sessions_location_idx
    on public.nu_event_sessions (session_building_id, session_floor_id, session_room_id);
create index if not exists nu_event_attendees_event_session_idx
    on public.nu_event_attendees (event_id, session_id);
create index if not exists nu_event_attendees_user_id_idx
    on public.nu_event_attendees (user_id);
create index if not exists nu_event_attendees_log_event_session_idx
    on public.nu_event_attendees_log (event_id, session_id);
create index if not exists nu_event_attendees_log_user_id_idx
    on public.nu_event_attendees_log (user_id);
create index if not exists nu_event_question_event_id_idx
    on public.nu_event_question (event_id);
create index if not exists nu_event_question_user_id_idx
    on public.nu_event_question (user_id);
create index if not exists nu_user_note_event_id_idx
    on public.nu_user_note (for_event_id);
create index if not exists nu_user_note_user_id_idx
    on public.nu_user_note (user_id);

comment on column public.nu_users."userID" is
    'Supabase Auth UUID from the CSV export. It is indexed but not unique because the source contains duplicate values.';
comment on column public.nu_event_attendees.session_id is
    'Logical reference to nu_event_sessions.id. No FK is enforced because the supplied export references missing sessions 36 and 37.';
comment on column public.nu_event_attendees.user_id is
    'Logical reference to nu_users.userID. No FK is enforced because the supplied user export is incomplete and contains duplicate auth UUIDs.';
comment on column public.nu_event_attendees_log.session_id is
    'Logical reference to nu_event_sessions.id. No FK is enforced because the supplied export references missing session 36.';
comment on column public.nu_event_attendees_log.user_id is
    'Logical reference to nu_users.userID. No FK is enforced because userID is not unique in the supplied export.';
comment on column public.nu_event_question.event_id is
    'Logical reference to nu_events.id. No FK is enforced because the supplied export references missing events 15 and 29.';
comment on column public.nu_event_question.user_id is
    'Logical reference to nu_users.userID. No FK is enforced because the supplied user export is incomplete.';
comment on column public.nu_user_note.for_event_id is
    'Logical reference to nu_events.id. No FK is enforced because the supplied export references missing event 29.';
comment on column public.nu_user_note.session_id is
    'Logical reference to nu_event_sessions.id.';
comment on column public.nu_user_note.user_id is
    'Logical reference to nu_users.userID. No FK is enforced because the supplied user export is incomplete.';
comment on column public.nu_events.event_host_user_id is
    'Logical reference to nu_users.id. No FK is enforced because the supplied export references missing user 4.';

-- The tables live in Supabase's API-exposed public schema. Keep them private until
-- explicit policies are designed for attendee and user personally identifiable data.
alter table public.nu_users enable row level security;
alter table public.nu_buildings enable row level security;
alter table public.nu_departments enable row level security;
alter table public.nu_floors enable row level security;
alter table public.nu_rooms enable row level security;
alter table public.nu_places enable row level security;
alter table public.nu_events enable row level security;
alter table public.nu_certificate_templates enable row level security;
alter table public.nu_certificates enable row level security;
alter table public.nu_certificate_audits enable row level security;
alter table public.nu_event_sessions enable row level security;
alter table public.nu_event_attendees enable row level security;
alter table public.nu_event_attendees_log enable row level security;
alter table public.nu_event_question enable row level security;
alter table public.nu_user_note enable row level security;

commit;
